name: drupal_9_actions
recipe: lamp
tooling:
  drush:
    description: Run drush commands
    service: appserver
    cmd: "/app/vendor/bin/drush --root=/app"
  install-site:
    description: Install A Drupal 9 site with the Testing Profile
    service: appserver
    cmd: >
      echo yes | /app/vendor/bin/drush si d9_test_profile
      --db-url="mysql://lamp:lamp@database:3306/lamp"
      --site-name="Web Express V2 Test Site"
      --account-name="admin" --account-pass="password"
      install_configure_form.enable_update_status_module=NULL
      install_configure_form.enable_update_status_emails=NULL
  behat:
    description: Run Behat Tests
    service: appserver
    cmd: "/app/vendor/bin/behat -c behat.local.yml"
  test:
    description: Run Unit Tests with phpunit
    service: appserver
    cmd: "composer test"
services:
  appserver:
    build:
      - composer install
config:
  php: '7.4'
  composer_version: '1.10.1'
  webroot: .
  database: mariadb
  xdebug: false
