name: Build and Test
on:
  push:
    branches: [main]
env:
  COMPOSER_MEMORY_LIMIT: -1
jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: drupal9
          MYSQL_DATABASE: drupal9
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
          tools: composer:v1
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      - name: Validate composer.json
        run: composer validate
      - name: Build Project
        run: composer install
      # - name: Install Site
      #   run: >
      #     echo yes | ./vendor/bin/drush si standard
      #     --db-url="mysql://root:drupal9@127.0.0.1:${{ job.services.mysql.ports[3306] }}/drupal9"
      #     --site-name="Testing Site Install"
      #     --account-name="admin" --account-pass="password"
      #     install_configure_form.enable_update_status_module=NULL
      #     install_configure_form.enable_update_status_emails=NULL
  phplint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code
        uses: overtrue/phplint@master
        with:
          path: ./modules/contrib
  phpunit:
    name: Test Site
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run PHP Unit
        run: ./vendor/bin/phpunit -c ./phpunit.xml --testsuite unit
        # env:
        #   DB_PORT: ${{ job.services.mysql.ports[3306] }}