name: Build and Test
on:
  push:
    branches: [main]
env:
  COMPOSER_MEMORY_LIMIT: -1
jobs:
  behat:
    name: Run Behat Tests
    runs-on: self-hosted
    steps:
      - name: Remove hardened permissions on sites directory
        run: sudo chmod -R 777 /home/vagrant/actions-runner/_work/d9-actions/d9-actions/sites
        continue-on-error: true
      - name: Cache Vendor Files
        uses: actions/cache@v2
        env:
          cache-name: cache-vendor
        with:
          path: ~/.cache/composer/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Validate composer.json
        run: /usr/share/composer validate
      - name: Install Dependencies
        run: /usr/share/composer install
      - name: Install Site
        run: >
          echo yes | ./vendor/bin/drush si d9_test_profile
          --db-url="mysql://root:drupal9@127.0.0.1:3306/drupal9"
          --site-name="Testing Site Install"
          --account-name="admin" --account-pass="password"
          install_configure_form.enable_update_status_module=NULL
          install_configure_form.enable_update_status_emails=NULL
      - name: Run Behat Tests
        run: /usr/share/composer behat
      - name: Run phpunit tests
        run: /usr/share/composer test
      - name: Lint code
        run: /usr/share/composer lint
  
  # phplint:
  #   name: Lint Code
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Validate composer.json
  #       run: /usr/share/composer validate
  #     - name: Build Project
  #       run: /usr/share/composer install
  #     - name: Lint Code
  #       run: /usr/share/composer lint

